# Generated by Django 2.2.16 on 2020-09-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20200927_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trasacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
